name: Build PRG

on:
  push:
    branches: [ main, test-github-actions ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cc65 make vice
      
    - name: Build PRG and D64
      run: make

    - name: Upload PRG and D64
      uses: actions/upload-artifact@v4
      with:
        name: diagnostic-rom
        path: |
          build/pet-ieee-loader.prg
          build/pet-ieee-loader.d64
