name: Build Loader and Sender

on:
  push:
    branches: [ main, test-github-actions ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Install CA65 and VICE dependencies
      run: sudo apt-get update && sudo apt-get install -y cc65 gawk make vice
    
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
    
    - name: Get short commit hash
      id: get_commit
      run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
    
    - name: Build PRG, D64, and sender (both debug and release)
      run: make all
    
    - name: Prepare binaries with unique names
      run: |
        mkdir -p artifacts
        cp loader/build/7c00-loader.prg artifacts/
        cp loader/build/loader.d64 artifacts/
        cp loader/build/test.bin artifacts/
        cp loader/build/9000-loader-rom.bin artifacts/
        cp loader/build/9000-loader-rom-1mbit.bin artifacts/
        cp sender/target/debug/sender artifacts/sender-debug-${{ env.COMMIT_HASH }}
        cp sender/target/release/sender artifacts/sender-release-${{ env.COMMIT_HASH }}
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: pet-ieee-builder-${{ env.COMMIT_HASH }}
        path: artifacts/